import { expect, test } from "@playwright/test";
const preview = process.env.CONTENT_PREVIEW_URL ?? "http://localhost:3101";
for (const width of [360, 390, 1440]) test(`TCP and DNS display outcomes only after the corresponding execution at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 844 });
  const url = (slug: string) => `${preview}/admin/preview/curricula/linux-networking/chapters/${slug}?lang=en`;
  await page.goto(url("sockets-ports-and-tcp"));
  const tcp = page.getByTestId("sockets-ports-and-tcp-figure");
  await expect(tcp.locator(".boundary-sequence-lens")).toHaveCount(0);
  await tcp.locator('[data-choice-value="recv"]').click();
  const pending = tcp.locator(".boundary-sequence-lens li.is-pending small");
  await expect(pending).toHaveCount(5);
  await expect(pending).toHaveText(Array(5).fill("Not executed yet"));
  await expect(tcp.locator('[data-node-id="server-app"] .journey-node-detail')).toHaveText("listen fd 3");
  await tcp.getByRole("button", { name: /02\s*Connect/ }).click();
  await expect(tcp.locator(".boundary-sequence-lens li.is-pending small")).toHaveCount(4);
  await tcp.getByRole("button", { name: /03\s*Accept/ }).click();
  await expect(tcp.locator('[data-node-id="server-app"] .journey-node-detail')).toContainText("accepted fd 4");
  await expect(tcp.locator(".boundary-sequence-lens li.is-current small")).toContainText("fd 4");
  for (const name of [/04\s*Send bytes/, /05\s*Observe ACK/, /06\s*Application recv/]) await tcp.getByRole("button", { name }).click();
  await expect(tcp).toHaveAttribute("data-mastered", "true");
  await expect(tcp.locator(".boundary-sequence-lens li.is-pending")).toHaveCount(0);
  await expect(tcp.locator(".boundary-sequence-lens li.is-current small")).toHaveText("5 · 0");

  await page.goto(url("dns-and-service-reachability"));
  const dns = page.getByTestId("dns-and-service-reachability-figure");
  await dns.locator('[data-choice-value="connect"]').click();
  const service = dns.locator('[data-node-id="service"] .journey-node-detail');
  const endpoint = dns.locator('[data-node-id="endpoint"] .journey-node-detail');
  const milestones = dns.locator(".state-timeline-lens li.is-reached");
  await expect(service).toHaveText("Response not observed");
  await expect(endpoint).toHaveText("Awaiting DNS answer");
  await expect(milestones).toHaveCount(1);
  await dns.getByRole("button", { name: /02\s*DNS answer/ }).click();
  await expect(endpoint).toHaveText("10.30.0.8:8080");
  await expect(milestones).toHaveCount(2);
  await dns.getByRole("button", { name: /03\s*Cache hit/ }).click();
  await expect(milestones).toHaveCount(2);
  await expect(service).not.toHaveText("HTTP 200");
  await dns.getByRole("button", { name: /04\s*Route to address/ }).click();
  await expect(milestones).toHaveCount(3);
  await dns.getByRole("button", { name: /05\s*TCP connect/ }).click();
  await expect(milestones).toHaveCount(4);
  await expect(service).toHaveText("Response not observed");
  await dns.getByRole("button", { name: /06\s*Verify response/ }).click();
  await expect(service).toHaveText("HTTP 200");
  await expect(milestones).toHaveCount(5);
  await expect(dns).toHaveAttribute("data-mastered", "true");
  await dns.getByRole("button", { name: "Reset lab", exact: true }).click();
  await expect(dns.locator(".state-timeline-lens")).toHaveCount(0);
  await dns.locator('[data-choice-value="connect"]').click();
  await expect(service).toHaveText("Response not observed");
  await expect(milestones).toHaveCount(1);
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
});
