import { useLocale } from "../../features/localization/localization";
import { ConceptCheckRenderer } from "../interactive/ConceptCheckRenderer";

export function SubnetConceptCheck({ onMasteryChange }: { onMasteryChange: (mastered: boolean) => void }) {
  const { locale } = useLocale();
  const t = (ko: string, en: string) => locale === "ko" ? ko : en;
  const questions = [
    { id: "same-link-decision", index: "01", prompt: t("10.20.0.2/24에서 10.20.0.44는 어떻게 전송할까요?", "How should 10.20.0.2/24 send to 10.20.0.44?"), options: [["arp-destination", t("목적지 자체를 ARP로 해석", "ARP for the destination itself")], ["use-default", t("기본 게이트웨이로 전송", "Send through the default gateway")], ["ask-remote-mac", t("원격 라우터에게 목적지 MAC 요청", "Ask a remote router for its MAC")]], correct: "arp-destination" },
    { id: "remote-next-hop", index: "02", prompt: t("203.0.113.20으로 보낼 때 ARP 대상은?", "What is the ARP target for 203.0.113.20?"), options: [["gateway-ip", "10.20.0.1"], ["remote-ip", "203.0.113.20"], ["host-ip", "10.20.0.2"]], correct: "gateway-ip" },
    { id: "frame-vs-packet", index: "03", prompt: t("원격 전송 프레임과 IP 패킷의 목적지는?", "What are the remote frame and IP packet destinations?"), options: [["gateway-mac-remote-ip", t("게이트웨이 MAC · 원격 IP", "Gateway MAC · remote IP")], ["remote-mac-remote-ip", t("원격 MAC · 원격 IP", "Remote MAC · remote IP")], ["gateway-mac-gateway-ip", t("게이트웨이 MAC · 게이트웨이 IP", "Gateway MAC · gateway IP")]], correct: "gateway-mac-remote-ip" },
    { id: "neighbor-role", index: "04", prompt: t("이웃 표가 저장하는 핵심 연결은?", "What mapping does the neighbor table hold?"), options: [["next-hop-ip-to-mac", t("같은 링크의 다음 홉 IP → MAC", "On-link next-hop IP → MAC")], ["dns-to-port", "DNS → port"], ["route-to-process", t("경로 → 프로세스", "Route → process")]], correct: "next-hop-ip-to-mac" },
    { id: "missing-default", index: "05", prompt: t("기본 경로가 없을 때 먼저 실패하는 단계는?", "What fails first when the default route is absent?"), options: [["route-selection", t("원격 목적지의 경로 선택", "Route selection for the remote destination")], ["tcp-ack", "TCP ACK"], ["dns-cache", "DNS cache"]], correct: "route-selection" },
  ].map((question) => ({ id: question.id, index: question.index, prompt: question.prompt, options: question.options.map(([value, label]) => ({ value, label })), correctAnswer: question.correct, answerLabel: t(`정답: ${question.options.find(([value]) => value === question.correct)?.[1]}`, `Answer: ${question.options.find(([value]) => value === question.correct)?.[1]}`), correctFeedback: t("경로 선택과 링크 전달의 경계를 정확히 읽었습니다.", "You separated route selection from link delivery."), incorrectFeedback: t("IP 목적지와 Ethernet 목적지, 그리고 ARP 대상을 다시 비교하세요.", "Compare the IP destination, Ethernet destination, and ARP target again.") }));
  return <ConceptCheckRenderer questions={questions} onMasteryChange={onMasteryChange} copy={{ kicker: "CHECK THE NEXT-HOP CONTRACT", title: t("IP 목적지와 다음 홉을 분리하세요", "Keep the IP destination separate from the next hop"), description: t("다섯 질문으로 /24, ARP, 기본 경로와 프레임 목적지를 점검합니다.", "Use five questions to check /24 boundaries, ARP, the default route, and frame destinations."), correct: t("정확합니다", "Correct"), incorrect: t("다시 확인하세요", "Check again"), checkAnswers: t("답 확인하기", "Check answers"), completed: t("개념 확인 완료", "Concept check complete"), retry: t("경로 그림을 다시 실행한 뒤 수정하세요.", "Run the path figure again, then revise your answers."), idle: t("다섯 답을 선택하세요.", "Choose all five answers.") }} />;
}
