import { Link } from "@tanstack/react-router";
import { useState } from "react";
import { INFRASTRUCTURE_CURRICULUM_SLUG, infrastructureChaptersEn, infrastructureChaptersKo } from "../../data/curriculum";
import { canCompleteAvailabilityChapter } from "../../features/infrastructure/availability-failure-domains";
import { useLocale } from "../../features/localization/localization";
import { AuthControls } from "../AuthControls";
import { ChapterToc } from "../ChapterToc";
import { CitationSection } from "../CitationSection";
import { CompleteChapter } from "../CompleteChapter";
import { LanguageSwitcher } from "../LanguageSwitcher";
import { usePublicationPreview } from "../PublicationPreview";
import { PublicLearningProof } from "../PublicLearningProof";
import { RootorialMark } from "../RootorialMark";
import { AvailabilityFailureDomainConceptCheck } from "./AvailabilityFailureDomainConceptCheck";
import { AvailabilityFailureDomainIncidentLab } from "./AvailabilityFailureDomainIncidentLab";
import { AvailabilityFailureDomainLab } from "./AvailabilityFailureDomainLab";
import "./availability-failure-domains.css";

const tocItems = {
  ko: [{ id: "domain", label: "replica와 failure domain" }, { id: "front-door", label: "gateway diversity" }, { id: "dependency", label: "dependency budget" }, { id: "recovery", label: "failover와 request loss" }, { id: "lab", label: "필수 가용성 lab" }, { id: "incidents", label: "네 correlated 사건" }, { id: "linux", label: "선택 Linux 관찰" }, { id: "transfer", label: "관측·용량으로 전이" }, { id: "check", label: "이해 확인" }],
  en: [{ id: "domain", label: "Replicas and failure domains" }, { id: "front-door", label: "Gateway diversity" }, { id: "dependency", label: "Dependency budget" }, { id: "recovery", label: "Failover and request loss" }, { id: "lab", label: "Required availability lab" }, { id: "incidents", label: "Four correlated incidents" }, { id: "linux", label: "Optional Linux observation" }, { id: "transfer", label: "Transfer to observability" }, { id: "check", label: "Concept check" }],
} as const;

export function AvailabilityFailureDomainsChapter({ learnerCount = 0 }: { learnerCount?: number }) {
  const { locale } = useLocale(); const isKo = locale === "ko"; const t = (ko: string, en: string) => isKo ? ko : en;
  const preview = usePublicationPreview(); const chapters = isKo ? infrastructureChaptersKo : infrastructureChaptersEn; const chapter = chapters.find(({ slug }) => slug === "availability-and-failure-domains")!;
  const [modes, setModes] = useState({ placement: false, recovery: false }); const [incidentsComplete, setIncidentsComplete] = useState(false); const [conceptsMastered, setConceptsMastered] = useState(false);
  const canComplete = canCompleteAvailabilityChapter({ placementComplete: modes.placement, recoveryComplete: modes.recovery, incidentsComplete, conceptsMastered });
  const previousHref = `/admin/preview/curricula/${INFRASTRUCTURE_CURRICULUM_SLUG}/chapters/service-discovery-and-load-balancing${isKo ? "" : "?lang=en"}`;
  const nextHref = `/admin/preview/curricula/${INFRASTRUCTURE_CURRICULUM_SLUG}/chapters/network-observability-and-capacity${isKo ? "" : "?lang=en"}`;
  return <main className="chapter-shell infrastructure-chapter-shell availability-chapter-shell"><header className="chapter-topbar"><Link className="wordmark" to="/" search={isKo ? {} : { lang: "en" }} aria-label={t("Rootorial 홈", "Rootorial home")}><RootorialMark className="wordmark-mark" /><span className="wordmark-name">Rootorial</span></Link><div className="chapter-header-actions"><span className="chapter-runtime-status"><span className="status-dot" aria-hidden="true" /> {chapter.runtime}</span><div className="chapter-progress-label"><span>CHAPTER 06</span><div className="mini-progress"><span style={{ width: "75%" }} /></div><span>6 / 8</span></div><LanguageSwitcher compact /><AuthControls compact /></div></header><div className="article-layout"><ChapterToc items={[...tocItems[locale]]} /><article className="lesson-article">
    <header className="lesson-hero infrastructure-lesson-hero availability-lesson-hero"><p className="eyebrow">REPLICA → FAILURE DOMAIN → DEPENDENCY → RECOVERY BUDGET · {isKo ? `약 ${chapter.estimatedMinutes}분` : `ABOUT ${chapter.estimatedMinutes} MIN`}</p><div className="lesson-number">06</div><h1>{chapter.title}</h1><p className="lesson-deck">{t("replica 수를 늘리는 데서 멈추지 않고, zone 하나를 실제로 제거했을 때 남는 gateway·app·database path와 request loss를 계산합니다. 독립 failure domain, bounded failover와 optional degraded mode를 하나의 가용성 contract로 조립합니다.", "Go beyond replica counts: remove one zone and calculate the remaining gateway, app, and database path plus request loss. Assemble independent failure domains, bounded failover, and an optional degraded mode into one availability contract.")}</p><PublicLearningProof count={learnerCount} locale={locale} scope="chapter" /><div className="lesson-objectives"><span>{t("학습 목표", "LEARNING OBJECTIVES")}</span><ul><li>{t("replica count와 failure-domain independence를 구분한다.", "Separate replica count from failure-domain independence.")}</li><li>{t("gateway와 database standby를 독립 zone에 배치한다.", "Place gateways and database standby in independent zones.")}</li><li>{t("optional dependency를 degraded mode로 격리한다.", "Isolate optional dependencies with a degraded mode.")}</li><li>{t("10,000 request trace로 99.5% target을 계산한다.", "Calculate a 99.5% target from a 10,000-request trace.")}</li></ul></div></header>
    <section className="article-section" id="domain"><div className="margin-label">01 — REPLICA COUNT IS NOT INDEPENDENCE</div><h2>{t("같은 zone의 replica 세 개는 zone 장애 앞에서 하나의 replica와 같습니다", "Three replicas in one zone behave like one under a zone failure")}</h2><p>{t("process crash에는 여러 replica가 도움이 되지만 rack 전원, zone network 또는 shared gateway 장애는 같은 경계의 모든 replica를 동시에 제거합니다. 설계 표에는 instance 수뿐 아니라 zone·rack·gateway owner를 함께 기록해야 합니다.", "Multiple replicas help with process crashes, but rack power, zone networking, or a shared gateway can remove every replica in the same boundary at once. Record zone, rack, and gateway owner alongside instance count.")}</p><div className="availability-principle"><strong>3 replicas × 1 zone</strong><span>≠</span><strong>3 independent failure domains</strong></div></section>
    <section className="article-section" id="front-door"><div className="margin-label">02 — THE FRONT DOOR IS PART OF THE PATH</div><h2>{t("app만 분산하고 gateway를 공유하면 ingress 전체가 correlated됩니다", "Spreading apps while sharing gateways leaves ingress correlated")}</h2><p>{t("service replica가 zone B와 C에 살아 있어도 client가 들어오는 gateway가 zone A에서 모두 사라지면 제공 가능한 path는 없습니다. gateway와 health-aware front door도 app placement와 같은 N-1 시나리오로 검증합니다.", "Even if service replicas survive in zones B and C, there is no service path when every client-facing gateway disappears with zone A. Verify gateways and the health-aware front door under the same N-1 scenario as app placement.")}</p></section>
    <section className="article-section" id="dependency"><div className="margin-label">03 — DEPENDENCY BUDGET AND DEGRADED MODE</div><h2>{t("optional dependency의 실패를 core response 실패로 승격하지 않습니다", "Do not promote an optional-dependency failure into a core-response failure")}</h2><p>{t("recommendations처럼 없어도 핵심 응답을 제공할 수 있는 dependency에는 짧은 timeout, bounded retry와 degraded response가 필요합니다. database처럼 required dependency는 독립 standby와 명시적 failover budget을 가져야 합니다.", "A dependency such as recommendations that is unnecessary for the core response needs a short timeout, bounded retry, and degraded response. A required dependency such as the database needs an independent standby and explicit failover budget.")}</p></section>
    <section className="article-section" id="recovery"><div className="margin-label">04 — RECOVERY BECOMES REQUEST LOSS</div><h2>{t("failover 시간을 served / total request로 변환합니다", "Translate failover time into served over total requests")}</h2><p>{t("이 장의 고정 trace는 zone A failure 동안 10,000개 request를 보냅니다. 올바른 설계는 20초 recovery window에서 40개를 잃고 9,960개를 제공해 99.6%를 달성합니다. 99.5% 목표를 넘지만 recovery가 길어지면 같은 placement도 실패합니다.", "This chapter sends 10,000 requests during a zone A failure. The working design loses 40 in a 20-second recovery window and serves 9,960 for 99.6%. That exceeds the 99.5% target, but a longer recovery makes the same placement fail.")}</p><div className="network-invariant-table" role="table" aria-label={t("가용성 계산", "Availability calculation")}><div role="row"><strong role="cell">SERVED</strong><span role="cell">9,960 / 10,000</span></div><div role="row"><strong role="cell">MEASURED</strong><span role="cell">99.60%</span></div><div role="row"><strong role="cell">TARGET</strong><span role="cell">≥ 99.50%</span></div></div></section>
    <section className="article-section" id="lab"><div className="margin-label">05 — REQUIRED FAILURE-DOMAIN LAB</div><h2>{t("placement와 dependency recovery 두 mode를 통과하세요", "Pass both placement and dependency-recovery modes")}</h2><p>{t("zone A를 제거하기 전에 결과를 예측하고, 실행 후에만 최초 실패 boundary와 availability를 공개합니다. control을 바꾸면 해당 mode의 이전 grade가 무효화됩니다.", "Predict before removing zone A; only execution reveals the first failed boundary and measured availability. Changing a control invalidates the prior grade for that mode.")}</p><AvailabilityFailureDomainLab onCompletionChange={setModes} /></section>
    <section className="article-section" id="incidents"><div className="margin-label">06 — DEBUG FOUR AVAILABILITY INCIDENTS</div><h2>{t("scale-up 대신 correlated boundary를 분리합니다", "Separate correlated boundaries instead of scaling up")}</h2><p>{t("same-zone replica, shared gateway, co-located standby와 optional cascade를 같은 evaluator로 다시 실행합니다. 같은 zone에 instance를 더 추가하거나 retry를 늘리는 선택은 독립성을 만들지 못합니다.", "Re-execute same-zone replicas, a shared gateway, a co-located standby, and an optional cascade through the same evaluator. Adding instances in the same zone or more retries does not create independence.")}</p><AvailabilityFailureDomainIncidentLab onCompletionChange={setIncidentsComplete} /></section>
    <section className="article-section" id="linux"><div className="margin-label">07 — OPTIONAL LINUX OBSERVATION</div><h2>{t("runtime label과 실제 network path를 읽기 전용으로 대조합니다", "Compare runtime labels with the real network path using read-only evidence")}</h2><p>{t("실제 환경에서는 scheduler의 zone label만 믿지 말고 route, endpoint와 health evidence를 함께 기록하세요. 외부 cluster나 privileged shell은 완료 조건이 아닙니다.", "In a real environment, do not trust scheduler zone labels alone; record routes, endpoints, and health evidence together. An external cluster or privileged shell is not a completion requirement.")}</p><pre className="network-observation-command">{["ip route get <service-vip>", "ss -lnt", "getent ahosts <service-name>", "curl -fsS <health-endpoint>"].join("\n")}</pre></section>
    <section className="article-section" id="transfer"><div className="margin-label">08 — TRANSFER TO OBSERVABILITY AND CAPACITY</div><h2>{t("가용성 claim을 어느 namespace·window의 증거로 입증할지 정합니다", "Choose the namespace and time window that prove each availability claim")}</h2><div className="network-transfer-task"><strong>{t("전이 과제", "TRANSFER TASK")}</strong><p>{t("zone failover 20초 동안 gateway counter, packet capture와 app socket queue를 어디서 측정할지 적으세요. 절대 counter가 아니라 같은 window의 delta와 capacity headroom이 필요합니다.", "Identify where to measure gateway counters, packet captures, and app socket queues during the 20-second zone failover. Use same-window deltas and capacity headroom, not absolute counters.")}</p></div></section>
    <section className="article-section concept-check" id="check"><div className="margin-label">09 — CONCEPT CHECK</div><AvailabilityFailureDomainConceptCheck onMasteryChange={setConceptsMastered} /><div className="network-completion-checklist" role="status" aria-live="polite"><span className={modes.placement ? "is-complete" : undefined}>{modes.placement ? "✓" : "○"} {t("domain placement", "Domain placement")}</span><span className={modes.recovery ? "is-complete" : undefined}>{modes.recovery ? "✓" : "○"} {t("dependency recovery", "Dependency recovery")}</span><span className={incidentsComplete ? "is-complete" : undefined}>{incidentsComplete ? "✓" : "○"} {t("네 가용성 사건", "Four availability incidents")}</span><span className={conceptsMastered ? "is-complete" : undefined}>{conceptsMastered ? "✓" : "○"} {t("다섯 개념", "Five concepts")}</span></div><CompleteChapter curriculumSlug={INFRASTRUCTURE_CURRICULUM_SLUG} slug="availability-and-failure-domains" canComplete={canComplete} lockedMessage={t("두 mode, 네 사건과 다섯 개념을 모두 완료하세요.", "Complete both modes, four incidents, and all five concepts.")} />    </section>
    <CitationSection citations={[{title:"Designing Data-Intensive Applications (Kleppmann, 2017)",url:"https://dataintensive.net/"},{title:"Site Reliability Engineering (Google SRE Book)",url:"https://sre.google/sre-book/table-of-contents/"}]} />
    <nav className="chapter-bottom-nav" aria-label={t("챕터 이동", "Chapter navigation")}>{preview ? <a href={previousHref}>← {t("이전: 서비스 탐색과 load balancing", "Previous: Service discovery and load balancing")}</a> : <span>← {t("이전: 서비스 탐색", "Previous: Service discovery")}</span>}{preview ? <a href={nextHref}>{t("다음: 네트워크 관측과 용량", "Next: Network observability and capacity")} →</a> : <span>{t("다음: 네트워크 관측과 용량", "Next: Network observability and capacity")} →</span>}</nav>
  </article></div></main>;
}
