import { infrastructureAvailabilityQuestions } from "../../features/chapters/chapter-registry";
import { useLocale } from "../../features/localization/localization";
import { useLearningAnalytics } from "../LearningAnalyticsProvider";
import { ConceptCheckRenderer, type ConceptQuestionSpec } from "../interactive/ConceptCheckRenderer";

type QuestionId = keyof typeof infrastructureAvailabilityQuestions;

export function AvailabilityFailureDomainConceptCheck({ onMasteryChange }: { onMasteryChange: (mastered: boolean) => void }) {
  const { locale } = useLocale();
  const t = (ko: string, en: string) => locale === "ko" ? ko : en;
  const { recordAnswers } = useLearningAnalytics();
  const specs: Array<{ id: QuestionId; prompt: [string, string]; options: Array<[string, string, string]> }> = [
    { id: "failure-domain-diversity", prompt: ["replica 세 개가 같은 zone에 있을 때 zone 장애에 대한 가용성은?", "What availability do three same-zone replicas provide against a zone failure?"], options: [["replica-count-is-enough", "replica 수만큼 독립성이 증가", "independence grows with replica count"], ["replicas-must-span-failure-domains", "replica가 서로 다른 failure domain에 있어야 함", "replicas must span failure domains"], ["load-balancer-removes-zone-risk", "load balancer가 zone risk를 제거", "a load balancer removes zone risk"]] },
    { id: "gateway-diversity", prompt: ["app이 분산돼도 gateway 둘이 zone A에만 있으면 남는 위험은?", "What risk remains when apps are spread but both gateways stay in zone A?"], options: [["front-door-remains-correlated", "front door가 하나의 correlated failure", "the front door remains one correlated failure"], ["gateway-size-prevents-outage", "gateway size가 outage를 방지", "gateway size prevents outage"], ["dns-ttl-creates-gateway", "DNS TTL이 gateway를 생성", "DNS TTL creates a gateway"]] },
    { id: "failover-budget", prompt: ["99.5% 목표에서 failover 시간을 설계할 때 필요한 것은?", "What is required when designing failover time for a 99.5% target?"], options: [["retry-until-success", "성공할 때까지 무제한 retry", "retry without limit until success"], ["hide-loss-from-metric", "loss를 metric에서 제외", "exclude loss from the metric"], ["bound-recovery-and-request-loss", "recovery 시간과 request loss를 명시적으로 제한", "explicitly bound recovery time and request loss"]] },
    { id: "dependency-budget", prompt: ["optional 추천 서비스가 실패했을 때 core response를 지키는 설계는?", "Which design protects the core response when optional recommendations fail?"], options: [["make-every-dependency-required", "모든 dependency를 required로 지정", "make every dependency required"], ["optional-dependency-has-degraded-mode", "optional dependency에 degraded mode 제공", "give the optional dependency a degraded mode"], ["retry-multiplies-availability", "retry가 availability를 자동 증가", "retries automatically multiply availability"]] },
    { id: "availability-math", prompt: ["10,000개 중 9,960개 request가 제공되면 측정 가용성은?", "If 9,960 of 10,000 requests are served, what is measured availability?"], options: [["served-over-total-is-99-6", "served / total = 99.6%", "served / total = 99.6%"], ["replicas-over-zones-is-150", "replicas / zones = 150%", "replicas / zones = 150%"], ["failover-seconds-is-percent", "failover seconds를 percent로 사용", "use failover seconds as percent"]] },
  ];
  const questions: Array<ConceptQuestionSpec<QuestionId>> = specs.map((spec, index) => ({ id: spec.id, index: String(index + 1).padStart(2, "0"), prompt: t(...spec.prompt), options: spec.options.map(([value, ko, en]) => ({ value, label: t(ko, en) })), correctAnswer: infrastructureAvailabilityQuestions[spec.id].correctAnswer, answerLabel: t("정답: 독립 domain, bounded recovery와 degraded mode", "Answer: independent domains, bounded recovery, and degraded mode"), correctFeedback: t("맞았습니다. replica count를 실제 실패 경계와 request budget으로 변환했습니다.", "Correct. You translated replica count into real failure boundaries and request budgets."), incorrectFeedback: t("zone 하나를 제거한 뒤 남는 gateway·replica·dependency를 다시 추적하세요.", "Remove one zone and retrace the remaining gateways, replicas, and dependencies.") }));
  return <ConceptCheckRenderer questions={questions} onMasteryChange={onMasteryChange} onSubmitAttempt={recordAnswers} copy={{ kicker: "DOMAIN → FAILURE → RECOVERY → SERVED REQUESTS", title: t("가용성 설계 contract를 판정하세요", "Judge the availability design contract"), description: t("두 mode, 네 사건과 다섯 개념을 모두 완료하세요.", "Complete both modes, four incidents, and all five concepts."), correct: t("failure domain과 recovery budget을 구분했습니다", "Failure domains and recovery budgets are separated"), incorrect: t("correlated placement와 optional dependency를 다시 확인하세요", "Recheck correlated placement and optional dependencies"), checkAnswers: t("가용성 판단 확인", "Check availability decisions"), completed: t("이해 확인 완료 — 두 필수 활동의 상태를 확인하세요.", "Concept check complete — verify both required activities."), retry: t("하나 이상의 가용성 invariant가 아직 섞여 있습니다.", "One or more availability invariants are still mixed."), idle: t("다섯 답을 고른 뒤 N-1 design을 확인하세요.", "Choose all five answers, then check the N-1 design.") }} />;
}
