/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperimentsLinuxRouteImport } from './routes/experiments.linux'
import { Route as CurriculaCurriculumSlugRouteImport } from './routes/curricula.$curriculumSlug'
import { Route as ChaptersVectorsRouteImport } from './routes/chapters.vectors'
import { Route as AdminPreviewCurriculaIndexRouteImport } from './routes/admin_.preview.curricula.index'
import { Route as CurriculaCurriculumSlugChaptersChapterSlugRouteImport } from './routes/curricula.$curriculumSlug_.chapters.$chapterSlug'
import { Route as AdminPreviewCurriculaCurriculumSlugRouteImport } from './routes/admin_.preview.curricula.$curriculumSlug'
import { Route as AdminPreviewCurriculaCurriculumSlugChaptersChapterSlugRouteImport } from './routes/admin_.preview.curricula.$curriculumSlug_.chapters.$chapterSlug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsLinuxRoute = ExperimentsLinuxRouteImport.update({
  id: '/experiments/linux',
  path: '/experiments/linux',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculaCurriculumSlugRoute = CurriculaCurriculumSlugRouteImport.update({
  id: '/curricula/$curriculumSlug',
  path: '/curricula/$curriculumSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersVectorsRoute = ChaptersVectorsRouteImport.update({
  id: '/chapters/vectors',
  path: '/chapters/vectors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreviewCurriculaIndexRoute =
  AdminPreviewCurriculaIndexRouteImport.update({
    id: '/admin_/preview/curricula/',
    path: '/admin/preview/curricula/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CurriculaCurriculumSlugChaptersChapterSlugRoute =
  CurriculaCurriculumSlugChaptersChapterSlugRouteImport.update({
    id: '/curricula/$curriculumSlug_/chapters/$chapterSlug',
    path: '/curricula/$curriculumSlug/chapters/$chapterSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPreviewCurriculaCurriculumSlugRoute =
  AdminPreviewCurriculaCurriculumSlugRouteImport.update({
    id: '/admin_/preview/curricula/$curriculumSlug',
    path: '/admin/preview/curricula/$curriculumSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPreviewCurriculaCurriculumSlugChaptersChapterSlugRoute =
  AdminPreviewCurriculaCurriculumSlugChaptersChapterSlugRouteImport.update({
    id: '/admin_/preview/curricula/$curriculumSlug_/chapters/$chapterSlug',
    path: '/admin/preview/curricula/$curriculumSlug/chapters/$chapterSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chapters/vectors': typeof ChaptersVectorsRoute
  '/curricula/$curriculumSlug': typeof CurriculaCurriculumSlugRoute
  '/experiments/linux': typeof ExperimentsLinuxRoute
  '/admin/preview/curricula/$curriculumSlug': typeof AdminPreviewCurriculaCurriculumSlugRoute
  '/curricula/$curriculumSlug/chapters/$chapterSlug': typeof CurriculaCurriculumSlugChaptersChapterSlugRoute
  '/admin/preview/curricula/': typeof AdminPreviewCurriculaIndexRoute
  '/admin/preview/curricula/$curriculumSlug/chapters/$chapterSlug': typeof AdminPreviewCurriculaCurriculumSlugChaptersChapterSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chapters/vectors': typeof ChaptersVectorsRoute
  '/curricula/$curriculumSlug': typeof CurriculaCurriculumSlugRoute
  '/experiments/linux': typeof ExperimentsLinuxRoute
  '/admin/preview/curricula/$curriculumSlug': typeof AdminPreviewCurriculaCurriculumSlugRoute
  '/curricula/$curriculumSlug/chapters/$chapterSlug': typeof CurriculaCurriculumSlugChaptersChapterSlugRoute
  '/admin/preview/curricula': typeof AdminPreviewCurriculaIndexRoute
  '/admin/preview/curricula/$curriculumSlug/chapters/$chapterSlug': typeof AdminPreviewCurriculaCurriculumSlugChaptersChapterSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chapters/vectors': typeof ChaptersVectorsRoute
  '/curricula/$curriculumSlug': typeof CurriculaCurriculumSlugRoute
  '/experiments/linux': typeof ExperimentsLinuxRoute
  '/admin_/preview/curricula/$curriculumSlug': typeof AdminPreviewCurriculaCurriculumSlugRoute
  '/curricula/$curriculumSlug_/chapters/$chapterSlug': typeof CurriculaCurriculumSlugChaptersChapterSlugRoute
  '/admin_/preview/curricula/': typeof AdminPreviewCurriculaIndexRoute
  '/admin_/preview/curricula/$curriculumSlug_/chapters/$chapterSlug': typeof AdminPreviewCurriculaCurriculumSlugChaptersChapterSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chapters/vectors'
    | '/curricula/$curriculumSlug'
    | '/experiments/linux'
    | '/admin/preview/curricula/$curriculumSlug'
    | '/curricula/$curriculumSlug/chapters/$chapterSlug'
    | '/admin/preview/curricula/'
    | '/admin/preview/curricula/$curriculumSlug/chapters/$chapterSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chapters/vectors'
    | '/curricula/$curriculumSlug'
    | '/experiments/linux'
    | '/admin/preview/curricula/$curriculumSlug'
    | '/curricula/$curriculumSlug/chapters/$chapterSlug'
    | '/admin/preview/curricula'
    | '/admin/preview/curricula/$curriculumSlug/chapters/$chapterSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chapters/vectors'
    | '/curricula/$curriculumSlug'
    | '/experiments/linux'
    | '/admin_/preview/curricula/$curriculumSlug'
    | '/curricula/$curriculumSlug_/chapters/$chapterSlug'
    | '/admin_/preview/curricula/'
    | '/admin_/preview/curricula/$curriculumSlug_/chapters/$chapterSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChaptersVectorsRoute: typeof ChaptersVectorsRoute
  CurriculaCurriculumSlugRoute: typeof CurriculaCurriculumSlugRoute
  ExperimentsLinuxRoute: typeof ExperimentsLinuxRoute
  AdminPreviewCurriculaCurriculumSlugRoute: typeof AdminPreviewCurriculaCurriculumSlugRoute
  CurriculaCurriculumSlugChaptersChapterSlugRoute: typeof CurriculaCurriculumSlugChaptersChapterSlugRoute
  AdminPreviewCurriculaIndexRoute: typeof AdminPreviewCurriculaIndexRoute
  AdminPreviewCurriculaCurriculumSlugChaptersChapterSlugRoute: typeof AdminPreviewCurriculaCurriculumSlugChaptersChapterSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/linux': {
      id: '/experiments/linux'
      path: '/experiments/linux'
      fullPath: '/experiments/linux'
      preLoaderRoute: typeof ExperimentsLinuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curricula/$curriculumSlug': {
      id: '/curricula/$curriculumSlug'
      path: '/curricula/$curriculumSlug'
      fullPath: '/curricula/$curriculumSlug'
      preLoaderRoute: typeof CurriculaCurriculumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/vectors': {
      id: '/chapters/vectors'
      path: '/chapters/vectors'
      fullPath: '/chapters/vectors'
      preLoaderRoute: typeof ChaptersVectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/preview/curricula/': {
      id: '/admin_/preview/curricula/'
      path: '/admin/preview/curricula'
      fullPath: '/admin/preview/curricula/'
      preLoaderRoute: typeof AdminPreviewCurriculaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curricula/$curriculumSlug_/chapters/$chapterSlug': {
      id: '/curricula/$curriculumSlug_/chapters/$chapterSlug'
      path: '/curricula/$curriculumSlug/chapters/$chapterSlug'
      fullPath: '/curricula/$curriculumSlug/chapters/$chapterSlug'
      preLoaderRoute: typeof CurriculaCurriculumSlugChaptersChapterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/preview/curricula/$curriculumSlug': {
      id: '/admin_/preview/curricula/$curriculumSlug'
      path: '/admin/preview/curricula/$curriculumSlug'
      fullPath: '/admin/preview/curricula/$curriculumSlug'
      preLoaderRoute: typeof AdminPreviewCurriculaCurriculumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/preview/curricula/$curriculumSlug_/chapters/$chapterSlug': {
      id: '/admin_/preview/curricula/$curriculumSlug_/chapters/$chapterSlug'
      path: '/admin/preview/curricula/$curriculumSlug/chapters/$chapterSlug'
      fullPath: '/admin/preview/curricula/$curriculumSlug/chapters/$chapterSlug'
      preLoaderRoute: typeof AdminPreviewCurriculaCurriculumSlugChaptersChapterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChaptersVectorsRoute: ChaptersVectorsRoute,
  CurriculaCurriculumSlugRoute: CurriculaCurriculumSlugRoute,
  ExperimentsLinuxRoute: ExperimentsLinuxRoute,
  AdminPreviewCurriculaCurriculumSlugRoute:
    AdminPreviewCurriculaCurriculumSlugRoute,
  CurriculaCurriculumSlugChaptersChapterSlugRoute:
    CurriculaCurriculumSlugChaptersChapterSlugRoute,
  AdminPreviewCurriculaIndexRoute: AdminPreviewCurriculaIndexRoute,
  AdminPreviewCurriculaCurriculumSlugChaptersChapterSlugRoute:
    AdminPreviewCurriculaCurriculumSlugChaptersChapterSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
