/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CurriculaCurriculumSlugRouteImport } from './routes/curricula.$curriculumSlug'
import { Route as ChaptersVectorsRouteImport } from './routes/chapters.vectors'
import { Route as CurriculaCurriculumSlugChaptersChapterSlugRouteImport } from './routes/curricula.$curriculumSlug_.chapters.$chapterSlug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculaCurriculumSlugRoute = CurriculaCurriculumSlugRouteImport.update({
  id: '/curricula/$curriculumSlug',
  path: '/curricula/$curriculumSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersVectorsRoute = ChaptersVectorsRouteImport.update({
  id: '/chapters/vectors',
  path: '/chapters/vectors',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculaCurriculumSlugChaptersChapterSlugRoute =
  CurriculaCurriculumSlugChaptersChapterSlugRouteImport.update({
    id: '/curricula/$curriculumSlug_/chapters/$chapterSlug',
    path: '/curricula/$curriculumSlug/chapters/$chapterSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chapters/vectors': typeof ChaptersVectorsRoute
  '/curricula/$curriculumSlug': typeof CurriculaCurriculumSlugRoute
  '/curricula/$curriculumSlug/chapters/$chapterSlug': typeof CurriculaCurriculumSlugChaptersChapterSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chapters/vectors': typeof ChaptersVectorsRoute
  '/curricula/$curriculumSlug': typeof CurriculaCurriculumSlugRoute
  '/curricula/$curriculumSlug/chapters/$chapterSlug': typeof CurriculaCurriculumSlugChaptersChapterSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chapters/vectors': typeof ChaptersVectorsRoute
  '/curricula/$curriculumSlug': typeof CurriculaCurriculumSlugRoute
  '/curricula/$curriculumSlug_/chapters/$chapterSlug': typeof CurriculaCurriculumSlugChaptersChapterSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chapters/vectors'
    | '/curricula/$curriculumSlug'
    | '/curricula/$curriculumSlug/chapters/$chapterSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chapters/vectors'
    | '/curricula/$curriculumSlug'
    | '/curricula/$curriculumSlug/chapters/$chapterSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chapters/vectors'
    | '/curricula/$curriculumSlug'
    | '/curricula/$curriculumSlug_/chapters/$chapterSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChaptersVectorsRoute: typeof ChaptersVectorsRoute
  CurriculaCurriculumSlugRoute: typeof CurriculaCurriculumSlugRoute
  CurriculaCurriculumSlugChaptersChapterSlugRoute: typeof CurriculaCurriculumSlugChaptersChapterSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curricula/$curriculumSlug': {
      id: '/curricula/$curriculumSlug'
      path: '/curricula/$curriculumSlug'
      fullPath: '/curricula/$curriculumSlug'
      preLoaderRoute: typeof CurriculaCurriculumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/vectors': {
      id: '/chapters/vectors'
      path: '/chapters/vectors'
      fullPath: '/chapters/vectors'
      preLoaderRoute: typeof ChaptersVectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curricula/$curriculumSlug_/chapters/$chapterSlug': {
      id: '/curricula/$curriculumSlug_/chapters/$chapterSlug'
      path: '/curricula/$curriculumSlug/chapters/$chapterSlug'
      fullPath: '/curricula/$curriculumSlug/chapters/$chapterSlug'
      preLoaderRoute: typeof CurriculaCurriculumSlugChaptersChapterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChaptersVectorsRoute: ChaptersVectorsRoute,
  CurriculaCurriculumSlugRoute: CurriculaCurriculumSlugRoute,
  CurriculaCurriculumSlugChaptersChapterSlugRoute:
    CurriculaCurriculumSlugChaptersChapterSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
